# Generated by Django 4.2.7 on 2023-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ipam', '0068_move_l2vpn'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fhrpgroupassignment',
            index=models.Index(fields=['interface_type', 'interface_id'], name='ipam_fhrpgr_interfa_2acc3f_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(
                fields=['assigned_object_type', 'assigned_object_id'], name='ipam_ipaddr_assigne_890ab8_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='vlangroup',
            index=models.Index(fields=['scope_type', 'scope_id'], name='ipam_vlangr_scope_t_9da557_idx'),
        ),
    ]
