# Generated by Django 5.1.3 on 2025-02-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0076_natural_ordering'),
        ('tenancy', '0017_natural_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlangroup',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='vlan_groups',
                to='tenancy.tenant',
            ),
        ),
    ]
