# Generated by Django 5.2.8 on 2025-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0084_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='asnrange',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rir',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vlangroup',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
