# Generated by Django 5.2.7 on 2025-11-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0049_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='start_on_boot',
            field=models.CharField(default='off', max_length=32),
        ),
    ]
