# Generated by Django 5.2.8 on 2025-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0050_virtualmachine_start_on_boot'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustergroup',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clustertype',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
