# Generated by Django 5.0.6 on 2024-06-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wireless', '0001_squashed_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='wirelesslink',
            name='_abs_distance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wirelesslink',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='wirelesslink',
            name='distance_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
