# Generated by Django 5.0.9 on 2024-11-04 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0196_qinq_svlan'),
        ('wireless', '0010_charfield_null_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='wirelesslan',
            name='_location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_%(class)ss',
                to='dcim.location',
            ),
        ),
        migrations.AddField(
            model_name='wirelesslan',
            name='_region',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_%(class)ss',
                to='dcim.region',
            ),
        ),
        migrations.AddField(
            model_name='wirelesslan',
            name='_site',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_%(class)ss',
                to='dcim.site',
            ),
        ),
        migrations.AddField(
            model_name='wirelesslan',
            name='_site_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='_%(class)ss',
                to='dcim.sitegroup',
            ),
        ),
        migrations.AddField(
            model_name='wirelesslan',
            name='scope_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wirelesslan',
            name='scope_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='contenttypes.contenttype',
            ),
        ),
    ]
