# Generated by Django 5.0.9 on 2024-11-14 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0196_qinq_svlan'),
        ('wireless', '0011_wirelesslan__location_wirelesslan__region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirelesslan',
            name='_location',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.location'
            ),
        ),
        migrations.AlterField(
            model_name='wirelesslan',
            name='_region',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.region'
            ),
        ),
        migrations.AlterField(
            model_name='wirelesslan',
            name='_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='wirelesslan',
            name='_site_group',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.sitegroup'
            ),
        ),
    ]
