# Generated by Django 5.2.10 on 2026-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('users', '0015_owner'),
        ('wireless', '0017_gfk_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wirelesslangroup',
            index=models.Index(fields=['tree_id', 'lft'], name='wireless_wirelesslangroup_fbcd'),
        ),
    ]
