# Generated by Django 4.2.8 on 2024-01-05 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ipam', '0069_gfk_indexes'),
        ('vpn', '0002_move_l2vpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunneltermination',
            name='outside_ip',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='tunnel_terminations',
                to='ipam.ipaddress',
            ),
        ),
    ]
