# Generated by Django 5.2b1 on 2025-04-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0008_add_l2vpn_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='l2vpntermination',
            name='vpn_l2vpnte_assigne_9c55f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='tunneltermination',
            name='vpn_tunnelt_termina_c1f04b_idx',
        ),
    ]
