# Generated by Django 5.2.8 on 2025-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0010_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnelgroup',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
