# Generated by Django 4.2.7 on 2023-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tenancy', '0012_contactassignment_custom_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactassignment',
            index=models.Index(fields=['content_type', 'object_id'], name='tenancy_con_content_693ff4_idx'),
        ),
    ]
