# Generated by Django 5.2.10 on 2026-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('tenancy', '0022_add_comments_to_organizationalmodel'),
        ('users', '0015_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactgroup',
            index=models.Index(fields=['tree_id', 'lft'], name='tenancy_contactgroup_tree_d2ce'),
        ),
        migrations.AddIndex(
            model_name='tenantgroup',
            index=models.Index(fields=['tree_id', 'lft'], name='tenancy_tenantgroup_tree_ifebc'),
        ),
    ]
