# Generated by Django 4.2.5 on 2023-10-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0167_squashed_0182'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='exclude_from_utilization',
            field=models.BooleanField(default=False),
        ),
    ]
