# Generated by Django 4.2.6 on 2023-10-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0183_devicetype_exclude_from_utilization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='child_interfaces',
                to='dcim.interface',
            ),
        ),
    ]
