# Generated by Django 4.2.4 on 2024-03-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0185_gfk_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='facility',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
