# Generated by Django 5.0.3 on 2024-04-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0186_location_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vc_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
