# Generated by Django 5.0.9 on 2024-09-26 19:31

from django.db import migrations

import utilities.fields


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0192_inventoryitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='poweroutlet',
            name='color',
            field=utilities.fields.ColorField(blank=True, max_length=6),
        ),
    ]
