# Generated by Django 5.1.7 on 2025-03-25 18:06

import django.db.models.manager
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0203_add_rack_outer_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerole',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicerole',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicerole',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicerole',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicerole',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='dcim.devicerole',
            ),
        ),
        migrations.AddField(
            model_name='devicerole',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='devicerole',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='devicerole',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
