# Generated by Django 5.2b1 on 2025-04-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0206_load_module_type_profiles'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cabletermination',
            name='dcim_cablet_termina_884752_idx',
        ),
    ]
