# Generated by Django 5.2.8 on 2025-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0223_frontport_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemrole',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rackrole',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
