# Generated by Django 5.2.10 on 2026-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0225_gfk_indexes'),
        ('extras', '0134_owner'),
        ('tenancy', '0022_add_comments_to_organizationalmodel'),
        ('users', '0015_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicerole',
            index=models.Index(fields=['tree_id', 'lft'], name='dcim_devicerole_tree_id_lfbf11'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tree_id', 'lft'], name='dcim_inventoryitem_tree_id975c'),
        ),
        migrations.AddIndex(
            model_name='inventoryitemtemplate',
            index=models.Index(fields=['tree_id', 'lft'], name='dcim_inventoryitemtemplatedee0'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tree_id', 'lft'], name='dcim_location_tree_id_lft_idx'),
        ),
        migrations.AddIndex(
            model_name='modulebay',
            index=models.Index(fields=['tree_id', 'lft'], name='dcim_modulebay_tree_id_lft_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['tree_id', 'lft'], name='dcim_platform_tree_id_lft_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['tree_id', 'lft'], name='dcim_region_tree_id_lft_idx'),
        ),
        migrations.AddIndex(
            model_name='sitegroup',
            index=models.Index(fields=['tree_id', 'lft'], name='dcim_sitegroup_tree_id_lft_idx'),
        ),
    ]
