name: Update translation strings

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  LOCALE: "en"

jobs:
  makemessages:
    if: github.repository == 'netbox-community/netbox'
    runs-on: ubuntu-latest
    env:
      NETBOX_CONFIGURATION: netbox.configuration_testing

    steps:
    - name: Create app token
      uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
      id: app-token
      with:
        app-id: 1076524
        private-key: ${{ secrets.HOUSEKEEPING_SECRET_KEY }}

    - name: Check out repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
          token: ${{ steps.app-token.outputs.token }}

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.12

    - name: Install system dependencies
      run: sudo apt install -y gettext

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run makemessages
      run: python netbox/manage.py makemessages -l ${{ env.LOCALE }}

    - name: Commit changes
      uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
      with:
        add: 'netbox/translations/'
        default_author: github_actions
        message: 'Update source translation strings'
