# Generated by Django 4.2.5 on 2023-10-20 21:25

from django.db import migrations

import utilities.fields


class Migration(migrations.Migration):
    dependencies = [
        ('circuits', '0038_squashed_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuittype',
            name='color',
            field=utilities.fields.ColorField(blank=True, max_length=6),
        ),
    ]
