# Generated by Django 5.0.9 on 2024-09-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('circuits', '0044_circuit_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='_abs_distance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='circuit',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='circuit',
            name='distance_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
