# Generated by Django 5.2.8 on 2025-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0054_cable_connector_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitgroup',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='circuittype',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='virtualcircuittype',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
