# Generated by Django 5.2.4 on 2025-07-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_update_group_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('-created',)},
        ),
    ]
