# Generated by Django 4.2.7 on 2023-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('extras', '0102_move_configrevision'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['object_type', 'object_id'], name='extras_book_object__2df6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='imageattachment',
            index=models.Index(fields=['content_type', 'object_id'], name='extras_imag_content_94728e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(
                fields=['assigned_object_type', 'assigned_object_id'], name='extras_jour_assigne_76510f_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='objectchange',
            index=models.Index(
                fields=['changed_object_type', 'changed_object_id'], name='extras_obje_changed_927fe5_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='objectchange',
            index=models.Index(
                fields=['related_object_type', 'related_object_id'], name='extras_obje_related_bfcdef_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='stagedchange',
            index=models.Index(fields=['object_type', 'object_id'], name='extras_stag_object__4734d5_idx'),
        ),
    ]
