# Generated by Django 4.2.5 on 2023-12-08 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('extras', '0103_gfk_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagedchange',
            name='created',
        ),
        migrations.RemoveField(
            model_name='stagedchange',
            name='last_updated',
        ),
    ]
