# Generated by Django 4.2.8 on 2023-12-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('extras', '0104_stagedchange_remove_change_logging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='validation_maximum',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='validation_minimum',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
