# Generated by Django 4.2.9 on 2024-02-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('extras', '0106_bookmark_user_cascade_deletion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cachedvalue',
            index=models.Index(fields=['object_type', 'object_id'], name='extras_cachedvalue_object'),
        ),
    ]
