# Generated by Django 5.0.3 on 2024-04-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('extras', '0113_customfield_rename_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
