# Generated by Django 4.2.7 on 2023-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_configrevision'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['object_type', 'object_id'], name='core_job_object__c664ac_idx'),
        ),
    ]
