# Generated by Django 5.2.9 on 2026-01-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='queue_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
